name: educare
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev. Remove if you want to publish.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^27.2.5 # Add charts dependency for visualizations
  cupertino_icons: ^1.0.8 # Cupertino icons for iOS style icons

  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # For coding best practices
  fl_chart: ^0.50.0 # Use the latest version from pub.dev
  provider: ^6.0.5
  #pigeon: ^5.0.0
flutter:
  uses-material-design: true # Enabling material design icons
  
  # If you need to add assets (like images), define them here.
  

  # You can include fonts in your project by adding them under the "flutter" section.
  # Example:
  # fonts:
  #   - family: MyCustomFont
  #     fonts:
  #       - asset: fonts/MyCustomFont-Regular.ttf
  #       - asset: fonts/MyCustomFont-Bold.ttf
