// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGa4zlgg1t8O0gfyscoykm8hpGEQ0HL9s',
    appId: '1:482155083551:android:59e7fe7eecd5b7bc29e22a',
    messagingSenderId: '482155083551',
    projectId: 'educare-746e7',
    databaseURL: 'https://educare-746e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educare-746e7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS6CFvKXtk5HAz4nYv31L9_6yqIWhmlF8',
    appId: '1:482155083551:web:2cdebd60e400753429e22a',
    messagingSenderId: '482155083551',
    projectId: 'educare-746e7',
    authDomain: 'educare-746e7.firebaseapp.com',
    databaseURL: 'https://educare-746e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educare-746e7.firebasestorage.app',
    measurementId: 'G-Y3KH1BM5JJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArgZow3Gqlj_Cr3D5IXQl5XgAFIAr7iJA',
    appId: '1:482155083551:ios:7aea6e53c127e95529e22a',
    messagingSenderId: '482155083551',
    projectId: 'educare-746e7',
    databaseURL: 'https://educare-746e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educare-746e7.firebasestorage.app',
    iosBundleId: 'com.example.educare',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArgZow3Gqlj_Cr3D5IXQl5XgAFIAr7iJA',
    appId: '1:482155083551:ios:7aea6e53c127e95529e22a',
    messagingSenderId: '482155083551',
    projectId: 'educare-746e7',
    databaseURL: 'https://educare-746e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educare-746e7.firebasestorage.app',
    iosBundleId: 'com.example.educare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS6CFvKXtk5HAz4nYv31L9_6yqIWhmlF8',
    appId: '1:482155083551:web:7d95276fe7a0ea6529e22a',
    messagingSenderId: '482155083551',
    projectId: 'educare-746e7',
    authDomain: 'educare-746e7.firebaseapp.com',
    databaseURL: 'https://educare-746e7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'educare-746e7.firebasestorage.app',
    measurementId: 'G-2MWCP77HK2',
  );

}